apiVersion: v1
kind: Service
metadata:
  name: admin-svc
  labels:
    name: admin
  namespace: furex-backend
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
