---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dep
  labels:
    app: admin
  namespace: furex-backend
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        envFrom:
            - secretRef:
                name: doppler-token
        image: furextch/admin-service:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8801
          name: prom
      # resources:
      #   limits:
      #     cpu: 300m
      #     memory: 500Mi
      #   requests:
      #     cpu: 100m
      #     memory: 200Mi
